#!/bin/bash

# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SQL_TIMEOUT=10

if [ "$1" == "--lenient" ]; then
  ERROR_RESULT=0
else
  ERROR_RESULT=1
fi

if [ -z "${BUILD_CLOUDSQL_INSTANCES}" ]; then
  >&2 echo "ERROR: Invoked access_cloud_sql with no CloudSQL instances available"
  exit ${ERROR_RESULT}
fi

rm -f /tmp/cloud_sql_proxy.log
touch /tmp/cloud_sql_proxy.log
cloud_sql_proxy -dir=/cloudsql -instances=${BUILD_CLOUDSQL_INSTANCES} > /tmp/cloud_sql_proxy.log 2>&1 &
if (timeout ${SQL_TIMEOUT}s tail -f --lines=+1 /tmp/cloud_sql_proxy.log &) | grep -qe 'Ready for new connections'; then
  echo "Started cloud_sql_proxy."
else
  >&2 echo "ERROR: Failed to start cloud_sql_proxy"
  >&2 cat /tmp/cloud_sql_proxy.log
  exit ${ERROR_RESULT}
fi
