steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', '$_ASDF_BASE_IMAGE:$_TAG']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', '$_ASDF_BASE_IMAGE:$_TAG', 'elixir-asdf']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE:$_TAG',
           '--build-arg', 'nodejs_version=$_NODEJS_VERSION',
           '--build-arg', 'gcloud_version=$_GCLOUD_VERSION',
           '.']

images:
  - '$_IMAGE:$_TAG'
