steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/$_NAMESPACE/base:$_TAG']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/$_NAMESPACE/base:$_TAG', 'elixir-base']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_NAMESPACE/generate-dockerfile:$_TAG',
           '--build-arg', 'debian_image=gcr.io/$PROJECT_ID/$_NAMESPACE/debian:$_TAG',
           '--build-arg', 'base_image=gcr.io/$PROJECT_ID/$_NAMESPACE/base:$_TAG',
           '--build-arg', 'builder_image=gcr.io/$PROJECT_ID/$_NAMESPACE/builder:$_TAG',
           '.']

images:
  - 'gcr.io/$PROJECT_ID/$_NAMESPACE/generate-dockerfile:$_TAG'
