steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/$_NAMESPACE/debian:$_TAG']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/$_NAMESPACE/debian:$_TAG', 'elixir-debian']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_NAMESPACE/asdf:$_TAG', '.']

images:
  - 'gcr.io/$PROJECT_ID/$_NAMESPACE/asdf:$_TAG'
